.TH CSAVEGUI 1
.SH NAME
CSaveGUI \- ncurses "GUI" for CSave
.SH SYNOPSIS
.B CSaveGUI
.SH DESCRIPTION
.B CSaveGUI
works in a similar fasion to CSaveMenu (please check its manual entries for 
details on where the CSave executables should go). \fBThis program does not
work on anything but Unix.\fR For a more platform-independent solution, just
use CSaveMenu. This user interface is dialog-driven, and is modeled after 
ISPF for ease of use.
