.TH CSAVEMENU 1
.SH NAME
CSaveMenu \- terminal-independent CSave user interface
.SH SYNOPSIS
.B CSaveMenu
.SH DESCRIPTION
.B CSaveMenu
is a terminal-independent user interface for the CSave programs that should
work on everything. Please note that it invokes the CSave executables as they
would be in your shell path, so please check and make sure that they are.
On Unix, the CSave executables should be installed in /opt/csave/bin and that
directory should be added to your path. On Windows, C:\\Program Files\\CSave
should be in your path. For OS/2, C:\\csave will do. For VAX/VMS or OpenVMS,
DISK$USER:[CSAVE] is the default. This program does not work on VM/CMS.
