.TH ITEMLOOKUPTEST 1
.SH NAME
ItemLookupTest \- verify integrity of item lookup database
.SH SYNOPSIS
.B ItemLookupTest 
.SH DESCRIPTION
.B ItemLookupTest
will verify the integrity of the CSave item lookup database and tables.
This is a command-oriented program. If you compiled CSave without the 
-DPRODUCTION flag, it will look in the current directory for a subdirectory
named LookupTables that contains the lookup table database files. If the
files do not exist, errors will be thrown. If you compiled a "production"
build of CSave, it will look in the directory specified by -DPREFIX. The
default is /opt/csave/LookupTables. Please check the CSave Manual for details
on how to use this program.
