.TH PROFILEGENERATE 1
.SH NAME
ProfileGenerate \- edit profile save protobuf data
.SH SYNOPSIS
.B ProfileGenerate
\fBinput.proto\fR \fBedited.proto\fR
.SH DESCRIPTION
.B ProfileGenerate
allows you to edit a converted BL3 profile save. This is a command-oriented
program, and works the same way as \fBSaveGenerate(1)\fR. The commands for 
this program are listed in the CSave manual.
.SH OPTIONS
.br
input.proto \- the input protobuf file. Do not specify a .sav here!
.br
edited.proto \- the edited output file.
