.TH PROFILETOPROTO 1
.SH NAME
ProfileToProto \- convert binary profile save file to protobuf data
.SH SYNOPSIS
.B ProfileToProto
\fBinput.sav\fR [\fBplatform\fR]
.SH DESCRIPTION
.B ProfileToProto
will convert your BL3 profile.sav into a protobuf data stream suitable for
editing. Its functionality is very similar to \fBSaveToProto(1)\fR and uses
the same platform codes.
.SH OPTIONS
.br
input.sav \- the input save file.
.br
platform \- the optional platform code.
