.TH PROFILEUNPACK 1
.SH NAME
ProfileUnpack \- display information about a BL3 profile (in protobuf format)
.SH SYNOPSIS
.B SaveUnpack
\fBinput.proto\fR
.SH DESCRIPTION
.B SaveUnpack
will read through a profile save and display as much about it as it can.
The output is similar to \fBSaveUnpack(1)\fR.
.SH OPTIONS
.br
input.proto \- the input protobuf file. Do not specify a .sav here!
.br
