.TH PROTOTOPROFILE 1
.SH NAME
ProtoToProfile \- convert protobuf data for a profile save to a BL3 save
.SH SYNOPSIS
.B ProtoToProfile
\fBinput.proto\fR \fBdonor.sav\fR [\fBplatform\fR]
.SH DESCRIPTION
.B ProtoToProfile
will convert an edited protobuf-format profile into a binary format 
profile.sav file that can be used with BL3. Like \fBProtoToSave(1)\fR, you
will need to specify a donor file to use the header from.
.SH OPTIONS
.br
input.proto \- the input profile protobuf data.
.br
donor.sav \- the donor save file whose header will be used for the new file.
.br
platform \- the optional platform code.
