.TH PROTOTOSAVE 1
.SH NAME
ProtoToSave \- convert protobuf data to a BL3 save
.SH SYNOPSIS
.B ProtoToSave
\fBinput.proto\fR \fBdonor.sav\fR [\fBplatform\fR]
.SH DESCRIPTION
.B ProtoToSave
will convert edited protobuf data and a donor save file into a BL3 .sav file.
The reason you must have a donor save file is to get the header from it. This
program simply replaces the serialized and obsfucated data in an existing 
save file with protobuf data. Since the protobuf data itself does not contain
any information about the platform, game version, or any such required 
parameters, it is dependant on an external save file to salvage a header from.
.SH OPTIONS
.br
input.proto \- the input protobuf data.
.br
donor.sav \- the donor save file whose header will be used for the new file.
.br
platform \- the optional platform code.
