.TH READSAVEHEADER 1
.SH NAME
ReadSaveHeader \- read a BL3 save's header
.SH SYNOPSIS
.B ReadSaveHeader
\fBinput.sav\fR
.SH DESCRIPTION
.B ReadSaveHeader
will display information about a save, including its platform and version
number. This information might be useful for using \fBGenSaveHeader(1)\fR to
generate a custom "stub" save file for use with the save generation programs.
.SH OPTIONS
.br
input.sav - save file to analyze
