.TH SAVECONVERT 1
.SH NAME
SaveConvert \- convert BL3 .sav saves between platforms
.SH SYNOPSIS
.B SaveConvert
\fBinput.sav\fR \fBoutput.sav\fR \fBplatform_in\fR \fBplatform_out\fR
.SH DESCRIPTION
.B SaveConvert
will allow you to convert BL3 binary save files (.sav) between systems. The
reason this must be done is because the XOR bitmask and headers are different
for different platforms. At the moment, this program understands PC saves
for Epic Games Store and Steam, and PlayStation 4 saves. Other platforms are
NOT supported. Furthermore, it should be noted that \fBthis program does not
produce PS4 saves that you can put on a flash drive and stick into your
console.\fR For that, you will need to look elsewhere, and that is out of the
scope for CSave and its documentation. For a list of platform codes, please 
see \fBCSaveIntro(1)\fR.
.SH OPTIONS
.br
input.sav \- the input save file.
.br
output.sav \- the output save file.
.br
platform_in \- the platform code for the input save file.
.br
platform_out \- the platform code for the output save file.

