.TH SAVEUNPACK 1
.SH NAME
SaveUnpack \- display information about a BL3 save (in protobuf format)
.SH SYNOPSIS
.B SaveUnpack
\fBinput.proto\fR
.SH DESCRIPTION
.B SaveUnpack
will read through a save file and display as much about it as it can. This does
not output JSON data, as that is not really necessary here. For a BL3 save
editor that does output JSON, please see bl3-cli-saveedit. 
.SH OPTIONS
.br
input.proto \- the input protobuf file. Do not specify a .sav here!
.br
